[package]
edition = "2021"
name = "oxc-svelte"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.16.11", default-features = false, features = ["napi9"] }
napi-derive = "2.12.2"

oxc_allocator = "0.30.5"
oxc_ast = { version = "0.30.5", features = ["serialize"] }
oxc_diagnostics = "0.30.5"
oxc_parser = "0.30.5"
oxc_span = "0.30.5"
serde = "1.0.210"
serde_json = "1.0.128"

[patch.crates-io]
oxc_parser = { path = './target/patch/oxc_parser-0.30.5' }

[build-dependencies]
napi-build = "2.0.1"
anyhow = "1.0.89"
cargo = "0.82.0"
fs_extra = "1.3.0"

[profile.release]
lto = true
strip = "symbols"
