name: Docs

on:
  push:
    branches:
      - master
    paths:
      - site/content/**

permissions: {}

jobs:
  release:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: my-app-install token
        id: github-app
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: run deploy docs workflow
        uses: 'sveltejs/action-deploy-docs/dispatch@main'
        with:
          repo: 'svelte'
          branch: 'master'
          docs_path: 'site/content'
          token: ${{ steps.github-app.outputs.token }}
